In [67]:
import pandas as pd
data = pd.read_csv("wine.csv")
y = data['quality']
x = data.drop(['quality'], axis=1)
#data.head()
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.25, random_state=42 )

from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(6,5),
                    random_state=5,
                    verbose=True,
                    learning_rate_init= 0.01)
clf.fit(x_train,y_train)


Iteration 1, loss = 20.11451744
Iteration 2, loss = 10.84787675
Iteration 3, loss = 6.55556444
Iteration 4, loss = 4.62833060
Iteration 5, loss = 2.86952062
Iteration 6, loss = 2.16788956
Iteration 7, loss = 1.79510285
Iteration 8, loss = 1.50643080
Iteration 9, loss = 1.39582257
Iteration 10, loss = 1.33842867
Iteration 11, loss = 1.29943917
Iteration 12, loss = 1.28106199
Iteration 13, loss = 1.25934940
Iteration 14, loss = 1.24133964
Iteration 15, loss = 1.21429778
Iteration 16, loss = 1.20070078
Iteration 17, loss = 1.19438063
Iteration 18, loss = 1.18801833
Iteration 19, loss = 1.18131330
Iteration 20, loss = 1.17645959
Iteration 21, loss = 1.17349410
Iteration 22, loss = 1.16928084
Iteration 23, loss = 1.16661900
Iteration 24, loss = 1.16350493
Iteration 25, loss = 1.16099609
Iteration 26, loss = 1.16113508
Iteration 27, loss = 1.15983841
Iteration 28, loss = 1.15628321
Iteration 29, loss = 1.15961959
Iteration 30, loss = 1.16212186
Iteration 31, loss = 1.16084591
Iteration 32, l

d:\iii\srm\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


,"hidden_layer_sizes hidden_layer_sizes: array-like of shape(n_layers - 2,), default=(100,)The ith element represents the number of neurons in the ithhidden layer.","(6, ...)"
,"learning_rate_init learning_rate_init: float, default=0.001The initial learning rate used. It controls the step-sizein updating the weights. Only used when solver='sgd' or 'adam'.",0.01
,"random_state random_state: int, RandomState instance, default=NoneDetermines random number generation for weights and biasinitialization, train-test split if early stopping is used, and batchsampling when solver='sgd' or 'adam'.Pass an int for reproducible results across multiple function calls.See :term:`Glossary <random_state>`.",5
,"verbose verbose: bool, default=FalseWhether to print progress messages to stdout.",True
,"activation activation: {'identity', 'logistic', 'tanh', 'relu'}, default='relu'Activation function for the hidden layer.- 'identity', no-op activation, useful to implement linear bottleneck, returns f(x) = x- 'logistic', the logistic sigmoid function, returns f(x) = 1 / (1 + exp(-x)).- 'tanh', the hyperbolic tan function, returns f(x) = tanh(x).- 'relu', the rectified linear unit function, returns f(x) = max(0, x)",'relu'
,"solver solver: {'lbfgs', 'sgd', 'adam'}, default='adam'The solver for weight optimization.- 'lbfgs' is an optimizer in the family of quasi-Newton methods.- 'sgd' refers to stochastic gradient descent.- 'adam' refers to a stochastic gradient-based optimizer proposed by Kingma, Diederik, and Jimmy BaFor a comparison between Adam optimizer and SGD, see:ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_training_curves.py`.Note: The default solver 'adam' works pretty well on relativelylarge datasets (with thousands of training samples or more) in terms ofboth training time and validation score.For small datasets, however, 'lbfgs' can converge faster and performbetter.",'adam'
,"alpha alpha: float, default=0.0001Strength of the L2 regularization term. The L2 regularization termis divided by the sample size when added to the loss.For an example usage and visualization of varying regularization, see:ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_alpha.py`.",0.0001
,"batch_size batch_size: int, default='auto'Size of minibatches for stochastic optimizers.If the solver is 'lbfgs', the classifier will not use minibatch.When set to ""auto"", `batch_size=min(200, n_samples)`.",'auto'
,"learning_rate learning_rate: {'constant', 'invscaling', 'adaptive'}, default='constant'Learning rate schedule for weight updates.- 'constant' is a constant learning rate given by 'learning_rate_init'.- 'invscaling' gradually decreases the learning rate at each time step 't' using an inverse scaling exponent of 'power_t'. effective_learning_rate = learning_rate_init / pow(t, power_t)- 'adaptive' keeps the learning rate constant to 'learning_rate_init' as long as training loss keeps decreasing. Each time two consecutive epochs fail to decrease training loss by at least tol, or fail to increase validation score by at least tol if 'early_stopping' is on, the current learning rate is divided by 5.Only used when ``solver='sgd'``.",'constant'
,"power_t power_t: float, default=0.5The exponent for inverse scaling learning rate.It is used in updating effective learning rate when the learning_rateis set to 'invscaling'. Only used when solver='sgd'.",0.5
,"max_iter max_iter: int, default=200Maximum number of iterations. The solver iterates until convergence(determined by 'tol') or this number of iterations. For stochasticsolvers ('sgd', 'adam'), note that this determines the number of epochs(how many times each data point will be used), not the number ofgradient steps.",200


In [68]:
print(y_train.shape)
print(x_train.shape)
print(y_test.shape)
print(x_test.shape)

(1199,)
(1199, 11)
(400,)
(400, 11)


In [69]:
import tensorflow as tf
print(tf.__version__)

2.21.0


In [70]:
from sklearn.neural_network import MLPClassifier 
model=MLPClassifier(hidden_layer_sizes=(64,32),activation='relu',max_iter=5000)
model.fit(x_train,y_train)
print (model.score(x_test,y_test))

0.57


In [71]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred = model.predict(x_test)
confusion_matrix= confusion_matrix(y_test,y_pred)
print(confusion_matrix)


[[  0   0   1   0   0   0]
 [  0   0  12   1   0   0]
 [  0   0 114  47   3   0]
 [  0   0  59 105   5   0]
 [  0   0   4  35   9   0]
 [  0   0   0   4   1   0]]


In [72]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(64, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(6, activation='softmax'))
from tensorflow.keras.optimizers import Adam
model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam(learning_rate=0.01), metrics=['accuracy'])
model.summary()

d:\iii\srm\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_32 (Dense)                │ (None, 64)             │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_33 (Dense)                │ (None, 6)              │           390 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,158 (4.52 KB)

 Trainable params: 1,158 (4.52 KB)

 Non-trainable params: 0 (0.00 B)

In [73]:
print(x_train.shape)

(1199, 11)


In [74]:
print(model.predict(x_test))

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
[[2.0606423e-05 1.0339985e-08 4.8313672e-05 9.9993098e-01 1.1789550e-08
  1.3391052e-07]
 [2.0608421e-10 1.8540522e-17 1.8510797e-10 1.0000000e+00 1.7751509e-18
  1.5531191e-16]
 [6.5260450e-05 2.0885962e-07 3.1850711e-04 9.9961263e-01 3.2801597e-07
  3.1539614e-06]
 ...
 [1.2204487e-04 6.0011121e-07 3.2365843e-04 9.9954420e-01 9.6180042e-07
  8.4454568e-06]
 [3.3210902e-03 1.2822034e-04 2.4464261e-02 9.6881670e-01 1.3501908e-03
  1.9196131e-03]
 [1.1917391e-03 3.6043250e-05 2.4587816e-02 9.7246474e-01 5.9815182e-04
  1.1214321e-03]]


In [75]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(64, input_dim=x_train.shape[1], activation='relu'))#aset #[1] for column, with just shape (row, column)input is 11 in dat
model.add(Dense(6, activation='softmax'))#softmax because multiple classes
from tensorflow.keras.optimizers import Adam
model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam(learning_rate=0.01), metrics=['accuracy'])# regression mse rmse , loss = crossentropy; classification accuracy
y_train = y_train -3 
y_test= y_test -3
print(np.unique(y_train))

d:\iii\srm\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


NameError: name 'np' is not defined

In [ ]:
pred= model.predict(x_test)
pred=np.argmax(pred,axis=1)
pred=pred+3
print(pred)
model.save("wine_quality_model.h5")

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step


[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 6 6 6 5 6 6 6 6
 6 6 6 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 6 6 6 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6 6
 6 5 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]


In [76]:
import pandas as pd
bp=pd.read_csv("House_Rent_Dataset.csv")
y=bp['Rent']
x=bp.drop(['Rent','Posted On','Floor','Area Locality'],axis=1)
import category_encoders as ce
encoder=ce.LeaveOneOutEncoder(return_df=True)
X=encoder.fit_transform(x,y)

In [77]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)


In [78]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(32, input_shape=(8,), activation='relu'))
model.add(Dense(1, activation='relu'))
model.compile(optimizer='adam',loss='mean_squared_error', metrics=['mse'])
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2)


Epoch 1/100


d:\iii\srm\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8906099712.0000 - mse: 8906099712.0000 - val_loss: 4838007296.0000 - val_mse: 4838007296.0000
Epoch 2/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8906101760.0000 - mse: 8906101760.0000 - val_loss: 4838007296.0000 - val_mse: 4838007296.0000
Epoch 3/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8906100736.0000 - mse: 8906100736.0000 - val_loss: 4838007296.0000 - val_mse: 4838007296.0000
Epoch 4/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8906101760.0000 - mse: 8906101760.0000 - val_loss: 4838007296.0000 - val_mse: 4838007296.0000
Epoch 5/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8906101760.0000 - mse: 8906101760.0000 - val_loss: 4838007296.0000 - val_mse: 4838007296.0000
Epoch 6/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8906105856.0000 - mse: 8906105856.0000 - val_loss: 4838007296.0000 - val_mse: 4838007296.0000
Epoch 7/100
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8906103808.0000 - mse: 8906103808.0